; ESP32 clasico (DevKit WROOM)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^7.2.0
    madhephaestus/ESP32Servo@^3.0.6
build_flags =
    -DCORE_DEBUG_LEVEL=0

; ESP32-C3 Mini / Super Mini (USB nativo)
[env:esp32-c3-mini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
lib_deps =
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^7.2.0
    madhephaestus/ESP32Servo@^3.0.6
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_ESP32_C3_MINI=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; Entorno por defecto al ejecutar `pio run` sin -e
[platformio]
default_envs = esp32-c3-mini
